- Programs/cmd.c
Starting to play with custom commands...
> Add missing include required when adding custom commands.

- Programs/usb_linux.c
This code polls the open usbfs file isntead of relying on signals (note that we poll for output even for input requests). This is what libusb seems to be doing and has worked for me for a few days without any lockups.
> Poll the usbfs file instead of relying on signals for async input.

- Messages/fr.po
Now fr.po is up-to-date in respect to the template.  Translator
should be pinged to update.
> Regenerate fr.po with latest template content. (ml)

- Drivers/Braille/VisioBraille/vstp_main.c
Found by Oracle Parfait static analyzer tool.
> Fix off-by-one in vstp option handling

- Programs/brlapi_server.c
@sthibaul has already reviewed the code.
> Improve BrlAPI server's select

- Programs/brlapi_server.c
> Improve code layout in definition of API packet handlers.

- Programs/brlapi_server.c
> Make documentation of mutex locking order more extensible.

- Programs/brlapi.h.in
> Slightly improve the BrlAPI documentation.

- Drivers/Braille/XWindow/braille.c
Hello Dave,
This will be useful to be able to test more corner cases.
Samuel
> xw: Increase maximum number of columns from 80 to 88

- Drivers/Braille/XWindow/README
(A colleague of mine hadn't understood that one can redirect the XW output to another computer)
> Improve X redirection documentation for XW driver

- Drivers/Braille/XWindow/README
Hello again,
In my colleague case, it's actually easier to just redirect X through ssh, so let's document this too.
Cheers,
Samuel
> xw: document how to forward output through ssh

- Messages/brltty.pot
An update to the german messages translation is about to be prepared and will
be submitted later today.
> Update to the messages template (2 new strings). (ml)

- Programs/apitest.c
- Programs/brlapi_client.c
- Programs/brlapi_common.h
- Programs/brlapi_server.c
This opens the way for asynchronous packet reading.
> brlapi: Factorize packet reading function between server and client

- Headers/win_pthread.h
Define ETIMEDOUT to EAGAIN if it is not defined already.
pthread_cond_timedwait actually use absolute dates, not relative delays.
It should also return ETIMEDOUT instead of looping, on timeout.
Introduce sem_timedwait.
> win_pthread: fix timedout functions

- Programs/apitest.c
- Programs/brlapi.h.in
- Programs/brlapi_client.c
Rename brlapi_readKeyTimeout to brlapi_readKeyWithTimeout, make it
return 0 on timeout.
> brlapi_client: Fix API

- Programs/brlapi_client.c
when given a timeout, we need to use sem_timedwait with proper absolute
timeout instead of sem_wait, and drop the semaphore on timeout.
Also fix the condition for looping: no need to loop in EOF case, and we
don't want to loop in timeout condition.
> brlapi_client: Fix taking into account timeout in second reader

- Drivers/Screen/AtSpi2/screen.c
The current code was actually not working at all because the initial
sender is SPI2_DBUS_INTERFACE_REG with path SPI2_DBUS_PATH_ROOT, and its
children are applications with SPI2_DBUS_PATH_ROOT too, so when deciding
to recurse, we need to check for both the path and the sender, not only
the path, which may be the same for two sender and make use believe than
we have a loop right from the beginning between SPI2_DBUS_INTERFACE_REG
and applications.
It is however noticeable that some applications do not actually always
expose their widgets as tree, but sometimes as a clique!  We thus need to
take care not only of direct loops, but also loops to further ancestors,
and just stop recursing completely in that case, to avoid an exponential
number of lookups.
> atspi2: Fix looking for currently active widget

- Programs/xbrlapi.c
So that we can simulate any keysym, independently from the keyboard
layout, and notably characters only reachable with dead keys.
> xbrlapi: map unmapped keysyms to temporary keycodes

- Programs/brltty-ttb.c
following-up 0e48a3adfe9d ("brltty-ttb: Add half-dots XCompose output
format")
> brltty-ttb: Add right-hand half-dots XCompose output format

- Messages/it.po
I created the Italian translation, even though it is incomplete for now.
> Italian translation created

- Drivers/Screen/AtSpi2/screen.c
before calling GetText, which would trigger warnings in the application
when the text interface is not actually available.
> at-spi2: check for objects supporting the text interface

- Programs/apitest.c
- Programs/brlapi.h.in
- Programs/brlapi_server.c
and use them in server and apitest
> brlapi parameters: add type for each parameter

- Drivers/Braille/Virtual/braille.c
- Programs/serial_termios.c
- configure.ac
This fixes building on Haiku, not really tested yet as I don't have hardware available.
> Haiku port

- Autostart/X11/90xbrlapi.in
- Drivers/Screen/AtSpi2/a2_screen.c
- configure.ac
since program_directory may be "${exec_prefix}/bin" and exec_prefix may be
${prefix}.
> Fix relations with X

- Drivers/Screen/AtSpi2/a2_screen.c
Various AtSpi2 objects implementations may send us completely bogus
data, so we have to be defensive against erroneous offsets and lengths.
> atspi2: be robust against bogus offsets/lengths

- Drivers/Screen/AtSpi2/a2_screen.c
When the atspi2 driver receives a new X clipboard content and sets the
core's clipboard content, it would then notice the core clipboard content
change, and would previously try to set a new X clipboard content, thus
stealing ownership from the initial application. This was perturbing the
normal X copy/paste behavior.
> atspi2: avoid clipboard loop

- Programs/xbrlapi.c
> xbrlapi: Add -v option to enable debugging messages

- Programs/brlapi_server.c
> brlapi_server: allow initialization to terminate early

- Programs/xbrlapi.c
Xorg version 21 seems to refuse our remapping requests. Avoids
completely crashing in such case, and just let the synthesis be skipped.
> xbrlapi: Ignore keyboard remapping errors from X server

- Drivers/Screen/AtSpi2/a2_screen.c
We want to prevent libX11 from exiting itself, and rather clean things
up correctly.
> AtSpi2: Fix crash on X shutdown

- Bindings/Emacs/bindings.c
Also fix a leak and check more return values.
> Bring Emacs bindings error handling more inline with the rest of BRLTTY

- Tables/Contraction/de-wort.cti
⠨⠴⠃⠎⠍⠴⠅⠞⠲⠛⠹⠯⠺⠼⠞
⠨⠃⠊⠇⠙⠥⠎⠲⠛⠹⠓
⠨⠃⠗⠥⠹⠲⠛⠹⠥
⠨⠹⠖⠠⠉⠉⠲⠛⠹⠓
⠨⠙⠗⠩⠑⠨⠎⠲⠛⠹⠥
⠨⠫⠅⠭⠉⠎⠲⠛⠹⠧⠻⠞⠩⠇⠥
…
> Broaden the rule for "Impfungleichheit" to "ungleich" to cover more cases. (ml)

- Programs/brlapi_client.c
When e.g. readKeyWithTimeout is passed a zero timeout, we should not wait, but we should also still probe at least once. It is thus not enough to just check whether the deadline has passed, we also want to check whether we polled at least once before returning a timeout.
This is important if more than a millisecond elapses between getRealTime calls, in which case brlapi__doWaitForPacket would believe the deadline has expired already.
Also, extend delay to long type, to make sure it can hold the difference between timeval fields.
> brlapi_client: Make sure to poll at least once on non-blocking calls

- Programs/brlapi_server.c
Otherwise we cannot easily work on reproducing crashes which fuzzing is ongoing.
> brlapi: Make fuzzer respect the host parameter

- Programs/cmd_clipboard.c
Concatenating rectangular copy should be done vertically i.e. a CR
should be present to separate it from the existing clipboard content.
> ensure appending to clipboard with a rectangular copy inserts a CR

- Programs/brlapi_keyranges.c
This reverts commit c1996200f4e85d4370a3bb9462c4859790f4a9c3.
In general, we do need to separate out each bit processing. For instance xbrlapi's request to ignore
.first = BRLAPI_KEY_FLG(ControlMask|Mod1Mask),
.last  = BRLAPI_KEY_FLG(ControlMask|Mod1Mask)|~BRLAPI_KEY_FLAGS_MASK,
indeed has to generate 32 intervals to properly accept any flag combination that is not exactly ControlMask|Mod1Mask.
> Revert "brlapi: Simplify keyrange management"

- Bindings/Python/setup.py.in
Follow up of #433 
Reverts brltty/brltty#430
> Revert "python: Tell setuptools about using the limited API"

- Messages/Makefile.in
- Messages/TRANSLATORS
- Messages/ka.po
Hello,
Adding initial version of Georgian translation
In case of problems, feel free to contact me.
BR, Temuri
> po: Add Georgian translation

- Tables/Contraction/de-wort.cti
> Fix to German contraction table.

- Programs/Makefile.in
Fixes make install --shuffle (make ≥ 4.4)
> Add missing install dependencies

- Messages/brltty.pot
- Messages/de.po
- **Update the message catalog template.**
- **Update to the German messages template. (ml)**
> Update to the German messages template

- Drivers/Braille/XWindow/braille.c
This shows up as Mod2 in xkb state.
> XWindow: Fix opening menu with numlock on

- Documents/Manual-BrlAPI/English/BrlAPI.sgml
The paragraph was getting included in the title
> brlapi documentation: Fix rendering

- Drivers/Screen/AtSpi2/a2_screen.c
screen positions do not match with unicode codepoints, so we have to process the whole unicode content to determine screen position.
> AtSpi2: Fix taking into account tabs and combining characters

- Drivers/Screen/AtSpi2/a2_screen.c
So we can act at least as minimalistic screen reader, even if we set our priority to low to let another screen reader take over.
> AtSpi2: Show something even for widgets without text interface
