Drivers/Braille/BrailleMemo/braille.c, Drivers/Braille/HIMS/braille.c, Drivers/Braille/HandyTech/braille.c, Drivers/Braille/HumanWare/braille.c, Programs/usb_linux.c
This fixes a few warnings emitted by the LLVM/Clang static analyzer.
=> memcpy and mempcpy expect a nonnull argument. (ml)

Autostart/Systemd/brltty@.service.in
SystemCallArchitectures=native in brltty@.service does not work at least on
Raspbian with two different types of Raspberries, better remove it to avoid
other people tripping over this.
=> SystemCallArchitectures=native breaks the service on ARM for some reason. (ml)

Drivers/Braille/HandyTech/braille.c
The Joystick Keys are an exception to how key codes have worked until now. 
Relax the check for navigation key group to allow them to be mapped.
=> Fix Actilino Joystick key processing. (ml)

Headers/prologue.h, Headers/win_pthread.h, Programs/system_windows.c
The mingw-w64 fork of mingw can produce native amd64 Windows binaries,
however it isn't fully compatible with the 32-bit mingw. This commit fixes
some minor compatibility issues, which leads to it being able to build the
client-side brlapi.dll.
Firstly, the `usleep` function that is patched in by BRLTTY for certain
versions of mingw is unnecessary when using mingw-w64, as it is already
exposed by its own libc headers. Therefore, this commit prevents the
compilation of this function if the compiler is detected to be mingw-w64.
Secondly, the `timespec` struct is also already provided when the
mingw-w64 libc is used, so it's similarly excluded.
These two changes are sufficient to get the brlapi.dll itself to compile
(i.e. the `api` make target). The last change makes sure that the
`all-api` …
=> Allow an amd64 brlapi.dll to be built using mingw-w64

Messages/brltty.pot, mkpot
Adjusts the sed expression in mkpot and updates brltty.pot.
=> Recent versions of gettext apparently put several source refs on a single line

Drivers/Braille/EuroBraille/eutp_brl.c, Drivers/Braille/EuroBraille/eutp_transfer.c, Programs/beep_solaris.c, Programs/pcm_audio.c, configure.ac
These are patches we've been using to build the brltty-5.4 packages for Solaris.
=> Build fixes for Solaris

Drivers/Braille/Baum/braille.c
I think this was an accidental oversight?
=> Add an entry for BAUM_DEVICE_Orbit to baumDeviceOperations.

Bindings/Python/bindings.m4
This causes a build error on GCC7:
cc1: error: -Wformat-security ignored without -Wformat [-Werror=format-security]
It is also no longer necessary, as the bindings do not have format
security issues.
=> Drop -Wno-format from Python bindings

Documents/README.Bluetooth
"agent on" by itself is already enough to receive PINCode requests
for pairings initiated from this bluetoothctl session.
default-agent would redirect PINCode requests from other DBus sessions as well,
but this is not necessary in this scenario.
=> There is no need to register a default agent. (ml)

Drivers/Braille/EuroBraille/brldefs-eu.h, Drivers/Braille/EuroBraille/eu_esysiris.c
EsysLight80 is a new braille display likes Esys 80 but without keyboard.
Esytime Evolution is a new braille note likes Esytime but with bluetooth adapter.
These modifications allow brltty to work fine with these devices via USB port.
Thanks a lot to add this contribution.
=> Add support for "EsysLight80" and "EsytimeEvolution"

Tables/Input/bm/b9b10.kti
On Baum devices with b9 and b10 keys on the side of the joystick, both keys should be treated as space.
Currently, the key to the right (B10) is considered space, but the one on the left (B9) is considered backspace. For consistency it would be best to have both of them represent space. Backspace is still accessible with DOT 7.
=> Baum key left of d-pad as space.

Drivers/Braille/Inceptor/braille.c
The second and third parameters were reversed.
=> Fix call to memset in Inceptor driver

Drivers/Screen/AtSpi2/screen.c
Hello,
I'm seeing the brltty AtSpi2 driver getting hung due to some odd behavior from some application: it has some object which declares having itself as its own child, and thus brltty would loop indefinitely.
Samuel
=> a2: Make sure that the child is not the same as the parent to avoid recursing indefinitely.

Tables/Contraction/lt.ctb, Tables/Text/lt.ttb
This adds/updates Lithuanian Braille tables.
Please note that I haven't tested them as I'm not a Braille user myself, and I haven't stumbled upon any documentation on how to actually run the tests. Any help in that regard would be appreciated.
I've ported these tables from liblouis, but being relatively fresh, they are likely to change in future, especially the 8-dot one.
=> Added Lithuanian Braille tables ported from liblouis.

Tables/Contraction/lt.ctb, Tables/Contraction/spaces.cti
This adds to #106.
I've added a shared Contraction table with whitespace characters, included it in my Lithuanian table, and also defined a lot of characters I didn't define initially (I assumed that the Contraction table is somehow used "on top" of the Text table). I checked the output this time and it looks fine.
=> Fixed the Contraction table for Lithuanian.

Documents/Manual-BrlAPI/English/BrlAPI.sgml, Programs/brlapi_protocol.h
Remove remaining references to brlapi_getDriverId and the corresponding
packet type.
=> BrlAPI manual cleanup

configure.ac
Ports I/O is an i386-specific thing.  Many architectures don't have it.
While inb/outb are not real functions (they are filled in by the
optimizer according to the manpages), ioperm is, and can easily
be tested for to check if the platform actually has ports I/O.
=> Check for ioperm to make sure the platform supports ports I/O. (ml)

Documents/Manual-BRLTTY/English/driver-codes.sgml, Documents/Manual-BRLTTY/English/speech-drivers.sgml, Documents/Manual-BRLTTY/French/driver-codes.sgml, Documents/Manual-BRLTTY/French/speech-drivers.sgml, Documents/Manual-BRLTTY/Portuguese/BRLTTY.htm, Documents/Manual-BRLTTY/Portuguese/BRLTTY.txt, Documents/README.DOS, Documents/brltty.1.in, Documents/brltty.conf.in, Documents/speech-driver.csv, Drivers/Speech/eSpeak-NG/Makefile.in, Drivers/Speech/eSpeak-NG/README, Drivers/Speech/eSpeak-NG/speech.c, README, brltty.spec.in, cfg-android, cfg-darwin, cfg-dos, config.mk.in, configure.ac
It is mostly a copy of the eSpeak driver, hence I put the following to `Drivers/Speech/eSpeak-NG/Makefile.in`:
`DRIVER_DEVELOPERS = Nicolas Pitre <nico@fluxnic.net>, Ondřej Lysoněk <olysonek@redhat.com>`
=> Add support for eSpeak-NG

Programs/brlapi_server.c
In that case the server would indefinitely try to create the socket
inside the initrd root. It needs to use chdir() to escape from it once
the real root is mounted.
=> Fix BrlAPI socket creation when brltty is started from initrd

Bindings/Python/apitest.py, Bindings/Python/brlapi.pyx
so applications can be sure they have released the file descriptor and only
memory potentially remains until python garbage collection.
=> Add closeConnection() python method

Drivers/Screen/AtSpi/screen.c, Drivers/Screen/AtSpi2/screen.c
Brltty can not really be used alone to read a graphical desktop, Orca is
really needed to do any serious work, and it has much better support for
AtSpi.  Brltty however rocks in terminals, so it does make a lot of
sense to use it along Orca, but only for reading terminals.  It thus
makes sense to make this setup the default.
=> AtSpi/AtSpi2: default to reading terminal only

Bindings/Python/brlapi.pyx
Returning a char* means that \0 is used as end of string, while one does
sometimes need to have zeroes in the masks. Instead we can just tell
cython how long the string is, allowing it to contain zeroes. The
trailing zero is then useless.
=> python: fix returning attrAnd/Or values

Programs/auth.c
Tell polkit_unix_process_new_for_owner to get process start
time from /proc, so it matches what the CVE-2018-1116 fix finds.
=> Polkit auth: fix authentication failure with CVE-2018-1116 fix

mk4build
Some identifiers for includes and libs paths may contain digit, e.g.
X11_PACKAGE or ATSPI2_PACKAGE or GLIB2_PACKAGE...
Also detect those identifiers when doing cros-compilation, so that the
_FOR_BUILD variants are really created and do not clash with the target
variants.
Fixes:
http://autobuild.buildroot.org/results/a37/a37782b3cfc1a96cc129db8fade20a36a7b2d470/build-end.log
http://autobuild.buildroot.org/results/97e/97edc6a47d2140968e84b409cdc960604e5896f2/build-end.log
[...]
Signed-off-by: "Yann E. MORIN" <yann.morin.1998@free.fr>
=> buildsys: fix cross-compilation

Headers/datafile.h, Programs/brltty-ttb.c, Programs/datafile.c
This can be used for typing braille with one hand by pressing dots 1, 2, 3,
7 keys twice, the first time for dots 1, 2, 3, 7, and the second time for
dots 4, 5, 6, 8.
=> brltty-ttb: Add half-dots XCompose output format

Programs/brltty-ttb.c
To avoid getting out of sync between left and right parts, it can be
useful to use different keys for them.
following-up 0e48a3adfe9d ("brltty-ttb: Add half-dots XCompose output format")
=> brltty-ttb: Add left+right half-dots XCompose output format

Android/Application/res/values-cs/strings.xml
In one of previous updates some strings were added with wrong codepage, this commit fixes them to proper utf8. Also some capitalization was changed.
=> Fix wrong codepage and capitalization of czech translation

Programs/config.c, Programs/xbrlapi.c
instead of waiting for driver construction. This allows clients, notably
xbrlapi, to know that brltty is present, but the device is not plugged in,
and should thus stay around, ready to start working when the device is
plugged in. When brltty is not present, they will know it from the refused
connexion, and tell the user about it and exit.
=> Start API server during initialization

Headers/brl_dots.h, Programs/brltty-ttb.c
Some one-handed people are used to having to move their hand between
left and right part. Not having to move the hand is convenient, but they
are used to using the same key for dot1 and dot6, dot2 and dot5, dot3
and dot4, instead of dot1/dot4, dot2/dot4, dot3/dot6.
=> brltty-ttb: Add alternated half xcompose files

Programs/brlapi_server.c
To avoid spamming system logs when Orca tries to reconnect periodically
until a braille device is connected.
=> Reduce log level of API client connection

Programs/apitest.c
apitest needs to get the local parameter, not the global parameter
=> apitest: Fix getting retaindots

Programs/brlapi_client.c, Programs/brlapi_protocol.h
And remove compatibility code in ignore_accept_key_ranges for MAXPACKETSIZE,
we will assume that in practice this does not pose problem.
=> brlapi: Revert protocol version to 8

Bindings/Python/brlapi.pyx
An initial version of the C api was using a local parameter, which we
turned into a global parameter, but the Python API hadn't gotten updated
=> brlapi parameters: Fix python local parameter into global

Bindings/Python/bindings.m4
since cython (using python2) is being phased out.
=> Python bindings: also look for cython3

Bindings/Python/Makefile.in
By passing --quiet vs --verbose to python setup.py, we can respect the
largely-used V=1 make parameter, so e.g. Debian build logs contain all
build details.
=> python: respect V=1 make parameter

mk4build
In commit 0414ad2b4e8978a14343d920a5a1f11da892eaf3, mk4build was
modified to pass a number of *_FOR_BUILD variables down to the
configure script called for building the native tools.
However, this configure script also uses the pkg-config tool, and the
pkg-config to use for the native build and the cross build may be
different, so let's also pass PKG_CONFIG_FOR_BUILD down to the
sub-configure, as PKG_CONFIG, following the same logic as the other
variables.
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
=> mk4build: also pass PKG_CONFIG_FOR_BUILD to the native configure

Autostart/X11/60xbrlapi.in, Autostart/X11/90brltty.in, Autostart/X11/90xbrlapi.in, Programs/xbrlapi.c, configure.ac
xbrlapi now starts in the background by default after checking whether
it could connect to brlapi.
We can thus use its result to determine whether to start brltty with
the AtSpi2 driver automatically.
=> Fine-tune xbrlapi+brltty startup

configure.ac
This notably fixes getting mempcpy, which would otherwise be detected by
configure, but its prototype not taken from system headers.
=> Request extended standards on windows too

Programs/brlapi_server.c
On Windows, the default named pipe buffer size is actually very small.
We have to tell the OS which minimum size we want. Otherwise we can get
in a situation where both the server and the client are trying to send
data, but none of them is reading each other's output, thus a deadlock.
Making the output buffer large enough allows the server to make sure
that it can write its packets to the client without blocking, and get
back to reading data from the client.
=> brlapi: Make server have enough buffer for sending/receiving a packet

Programs/brlapi_client.c, config.h.in, configure.ac
Notably on gnome with Wayland, XDG_VTNR may not be getting defined. We
can however just directly ask logind which VT our process is running on.
=> libbrlapi: Automatically get VT nr from logind

Programs/brlapi_server.c
So that forwarding TCP port localhost:4101 also works on systems where
localhost resolve to ::1 too.
=> brlapi: Also listen on IPv6 by default

Programs/xbrlapi.c
The root window gets focus transiently when the window manager switches
windows etc. It is not generally useful to the user to get notified about
it, and is mostly perceived as glitches, so better only show names of real
windows.
=> xbrlapi: do not print the root window name

Bindings/OCaml/brlapi_stubs.c
Since OCaml 4.10 strings are immutable by default.
This affects the String_val() API, which returns a 'const char *'.
This affects the caml_named_value() API, which returns a 'const char *'.
Add backward compatible change to handle -safe-string and -unsafe-string.
ocamlc.opt -ccopt "-I. -I. -I./../../Programs -I../../Programs -I../../Headers -I./../.. -I../..  -I/usr/lib/jvm/java/include -I/usr/lib/jvm/java/include/linux  -D_DEFAULT_SOURCE -D_POSIX_C_SOURCE=2 -D_BSD_SOURCE -D_XOPEN_SOURCE=500 -D_XOPEN_SOURCE_EXTENDED -D_GNU_SOURCE -DHAVE_CONFIG_H -fomit-frame-pointer -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -std=gnu99 -Wall -Werror=format-security" -I ./../../Programs -I …
=> Handle OCaml safe-string

Programs/xsel.c
In the atspi2 use case, we do not directly use XPending or XNextEvent
since we let the core select on the X fd. The XSetSelectionOwner request
would then wait for the next incoming message, thus coming completely
out of sync, and disturbing the clipboard management.
=> xsel: Make sure to flush XSetSelectionOwner

Drivers/Screen/AtSpi2/a2_screen.c
We need to release curRows[i] before releasing curRows
We also need to release curRowLengths.
And we need to release all data when destroying the driver, before unloading
the module.
=> atspi2: fix releasing data

Drivers/Screen/AtSpi2/a2_screen.c
When we get invalid utf-8 data from getText or getName that contains \n,
we were previously setting length to -1, and later on curRows[i][len]='\n'
would thus use a negative offset. Setting the length to 0 allows to just
drop the invalid text.
=> atspi2: Fix ignoring invalid data

Drivers/Screen/AtSpi2/a2_screen.c
Most often we do not need to remove rows, avoid calling reallocs etc.
with the same size.
=> atspi2: avoid removing 0 rows

Programs/brlapi_server.c
Even if the alternate code without retaindot is the same as the code
with retaindot, we need to call whoGetsKey. Otherwise xbrlapi does not
get backspace keycodes: they produce the same keycode with/without
retaindot, but since xbrlapi sets retaindot to 0, it would not get them
from the first call.
=> brlapi: Fix backspace synthesis in xbrlapi

Drivers/Braille/BrlAPI/braille.c, Programs/brlapi_param.h, Programs/brlapi_server.c
This allows a client to easily disable its input and output.
=> brlapi: Add BRLAPI_PARAM_CLIENT_PRIORITY_DISABLE

Programs/xbrlapi.c
In practice int is usually fine, but better document that this is indeed
a variable to be written by the handler and read by the main thread.
=> xbrlapi: Use sig_atomic_t for signal-modified variable

Documents/Manual-BrlAPI/English/BrlAPI.sgml, Programs/brlapi.h.in
Once brlapi_enterTtyMode is called, brlapi_enterTtyMode cannot be called
until brlapi_leaveTtyMode is called.
=> brlapi: Fix documentation for brlapi_enterTtyMode

Bindings/Java/bindings.c, Bindings/OCaml/brlapi_stubs.c, Bindings/Python/brlapi.pyx, Bindings/Python/c_brlapi.pxd, Bindings/Tcl/bindings.c, Programs/brlapi.h.in, Programs/brlapi_client.c
And make bindings use it instead of brlapi_strerror.
=> brlapi_client: Add thead-safe brlapi_strerror_r

Bindings/Python/c_brlapi.pxd, Documents/Manual-BrlAPI/English/BrlAPI.sgml, Programs/brlapi.h.in, Programs/brlapi_client.c, Programs/brlapi_server.c
To simplify the client brlapi_write management, the server can manage
itself padding / truncating the text being displayed.
=> brlapi: Allow writes that fill up to the end of the display

Programs/brlapi_server.c
In case the braille table makes ' ' translated to non-blank.
=> brlapi_server: Make sure that write padding is completely blank

Bindings/Python/c_brlapi.pxd
The C code generated by cython will use the bitfields naturally.
=> brlapi python: Update brlapi_param_properties_t fields

Drivers/Screen/AtSpi2/a2_screen.c
This reverts commit 81cc72e023f6ca0fe6952d9b266ed937b38d28bc.
fstat on a unix socket does not actually get the socket inode status, so
that cannot be used for fixing the permissions.
=> Revert "Use fchmod (not chmod) to adjust the BrlAPI socket permissions. (dm)"

Programs/xsel.c
LibreOffice seems to insist on getting an array of atoms, not a string.
This is probably more compatible with older clients indeed.
=> xsel: Fix setting targets property format

configure.ac
When building the project with LLVM/Clang it is desirable to
be able to use the LLD linker as well as llvm-strip/ranlib
so replace the path-based hardcoded tool name search with a
more flexible AC_CHECK_TOOL search.
Signed-off-by: Adrian Ratiu <adrian.ratiu@collabora.com>
=> configure.ac: fix LD, STRIP and RANLIB hardcoding

Programs/brlapi_client.c
We were assuming that ret still contains the number of sessions, so we were
not supposed to overwrite it. We rather use an explicit separate variable
then.
=> brlapi_client: Fix using the number of sessions

Programs/brlapi_server.c
CHECKEXC returns on exception, this was previously done with the
brailleWindowMutex held. We actually do not need to keep the mutex held
while checking the size parameters.
=> brlapi server: Fix missing unlock on raising exception

Tools/pythoncmd
Fixes Debian's bug: https://bugs.debian.org/1007927
Debian adds a custom sysconfig scheme to system python installs, "posix_local". This is the default scheme, and it redirects local users' Python module installs to /usr/local even though Python is installed with a /usr prefix. Both are on Debian's python's sys.path module search path.
Previously this custom sysconfig scheme was specified in distutils.sysconfig, but not sysconfig itself. As distutils is being deprecated, the custom scheme is now specified in sysconfig, since Debian's Python 3.10 (3.10.2-4).
As far as I can see, pythoncmd is only used in detecting the installed system python, not determining where the built module will be installed, so this patch is sufficient. To control where the module is installed, the approach would …
=> Handle Debian's default posix_prefix sysconfig layout

Drivers/Screen/AtSpi2/a2_screen.c
Rather than letting setScreenKeyModifiers turn them into control-[A-Z],
because most X applications will consider those as shortcuts instead of
interpreting them as control characters.
=> AtSpi2: convert standard control characters into special keys

Drivers/Screen/AtSpi2/a2_screen.c
It seems some clipboard contents get \r instead of \n, so convert them as
well.
=> Atspi2: Also convert \r

Programs/brlapi_client.c
Since this is also defined there nowadays. That can be convenient in
e.g. a tmux.
Suggested-by: Mario Lang <mlang@blind.guru>
=> brlapi: Interpret XDG_VTNR on the text console as well

Bindings/Emacs/apitest, Bindings/Emacs/apitest.el, Bindings/Emacs/bindings.c
- Pass Emacs apitest command line arguments to brlapi-open-connection. (ml)
- Change brlapi-error data items such that the explanatory string comes first. (ml)
=> Emacs binding changes

Programs/brlapi_server.c
Better cast from the actual uint32_t member of the union, to avoid a
warning with -Wstrict-aliasing=1
=> brlapi: Fix uint32 casting

Drivers/Screen/TerminalEmulator/em_screen.c, Headers/scr_terminal.h, Programs/pty_screen.c, Programs/scr_emulator.c, Programs/scr_terminal.c
- terminal emulator: make rows directly indexable
- terminal emulator: shift row indices rather than whole memory when scrolling
=> terminal emulator scrolling optimization

Programs/brlapi_server.c
If the braille driver is not constructed, disp is NULL, and thus a BrlAPI GetModelIdentifier request would crash. Return an empty string instead in that case.
=> Fix crash on GetModelIdentifier while driver unconstructed

Programs/brlapi_server.c
The check for early exit from the for loop was wrong.
=> brlapi: Fix erroneous free on bogus parameter unregistration

Drivers/Screen/AtSpi2/a2_screen.c
We would otherwise get, here with ubsan:
```
brltty: report listener already registered: 5: a2CoreSelUpdated UndefinedBehaviorSanitizer:DEADLYSIGNAL
==2087615==ERROR: UndefinedBehaviorSanitizer: SEGV on unknown address 0x000000000000 (pc 0x56356b124850 bp 0x000000000000 sp 0x7fcc4d9fdbd8 T2087615) ==2087615==The signal is caused by a READ memory access. ==2087615==Hint: address points to the zero page.
#0 0x56356b124850 in unregisterReportListener /home/samy/brl/mielke-svn/brltty/Programs/./report.c:208:22
#1 0x7fcc5233f0ab in destruct_AtSpi2Screen /home/samy/brl/mielke-svn/brltty/Drivers/Screen/AtSpi2/./a2_screen.c:1574:5
#2 0x56356b15304d in destructRoutingScreen /home/samy/brl/mielke-svn/brltty/Programs/./scr.c:255:3
#3 0x56356b1542e9 in startRoutingProcess …
```
=> AtSpi2: Fix crash on routing request

Programs/brlapi_keyranges.c
There is no need to separate each bit processing: either we remove the full range because ~minFlags & maxFlags != 0, or we just clamp the permitted flags.
This avoids an exploding set of ranges when repeatedly removing intervals, as found by fuzzing.
=> brlapi: Simplify keyrange management

Programs/brlapi_server.c
In case a connection had already entered a tty, we should not free the windows, otherwise the core will try to display it, and crash.
Found by fuzzing.
=> brlapi: Do not free connection window when re-entering tty fails

Drivers/Braille/HandyTech/braille.c, Drivers/Braille/HandyTech/brldefs-ht.h, Tables/Input/ht/ac4.ktb
For Activator, the rockers have been replaced by navigation keys, some of which retain the keycodes also emitted by the rockers. The functionality should be identical to the six keys found on Basic Braille devices, so I have assigned them to Display1 up to Display6 just as Basic Braille does.
=> Modified keymaps for Activator to reflect latest firmware modifications.

Autostart/X11/90xbrlapi.in
When a distribution ships them separately they may not be available, and brltty would then flood logs with driver load failure warning every 5 seconds.
=> xbrlapi: Do not try to start brltty with ba+a2 when unavailable

Bindings/Python/brlapi.pyx
From Lukáš Tyrychtr:
“
Cython 3.0 started using the new Python object finalization APIs from PEP 442 ”
This means that `__del__` gets called even when raising an exception from `__init__`, while it was not before. To cope with both behaviors, we can set self.h to NULL to determine whether it still exists or not.
Thanks Lukáš Tyrychtr for the investigation and patch draft!
=> brlapi: Fix python crash on connection error

Programs/brlapi_server.c
We don't need to keep the lock while sending, and that can avoid interlock scenarii.
=> brlapi: Avoid holding the acceptedKeysMutex mutex while writing a key

Programs/scr_base.c, Programs/scr_driver.c
When e.g. brltty cannot load a screen driver, but can load the BrlAPI driver, we have to make sure to know that we have a low screen reading quality, otherwise the BrlAPI driver would consume braille keyboard events, without being able to do anything about them.
This notably fixes cursor routing and braille panning in Orca when xbrlapi is installed but the a2 screen driver is not installed.
=> screen: Set quality to low or none for base and no

Headers/prologue.h
It looks like when winerror.h is missing from prologue.h, BRLTTY can't be build with newer versions of the Windows SDK. This should resolve that.
=> Add winerror.h to prologue for Windows

Bindings/Python/Makefile.in, Windows/mkwin, Windows/winsetup
This adds support for Python 3.11:
- Several work to make distutils behave has been removed, e..g. copying vcruntime140.dll, patching cygwinccompiler.py . When we use the most recent version of Setuptools, this is no longer needed.
I've also seen the `RuntimeWarning: Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect` warning. I'm not sure what causes it, but I think it might have been caused by the build system using mingw32 for the build whereas it creates a wheel with msvc Python.
=> Add support for Python 3.11

Windows/brltty.nsi, appveyor.yml
As I have been struggling for ages to get a working windows build of BRLTTY for myself, I figured building the Windows version with Continuous Integration would be most helpful.
Appveyor has baked in support for msys1, so that seemed like a good starting point, and indeed, it works like a charm.
The bundled configuration for Appveyor builds BRLTTY and uses Python 3.11 for the Python bindings. The resulting zip and installer executable are uploaded as artifacts and can be fetched from the build after building.
i have also added Unicode false to the nsis script. This is the default behavior in the version of nsis that is used by the build system by default, but Appveyor has a newer version that has Unicode set to true by default. When we change Unicode to true, we get errors with …
=> Support building Windows version on Appveyor

Programs/brlapi_server.c
This deleted code is broken if the PAGE_SIZE define is removed (which it likely will be in the future), because <asm/page.h> doesn't exist in the Android NDK.
This file doesn't use PAGE_SIZE itself, but the code was originally added in 2012 in a9ed2d9ffb8ad9bd0209d2c264675d3ccf39f99c apparently as a workaround for a bug in the pthread.h header. That's certainly no longer relevant.
=> Delete some broken ifdeffery for android.

Programs/Makefile.in, Programs/brlapi_client.c, Programs/file.c, Programs/usb_solaris.c, config.h.in, configure.ac
gcc 14 is stricter about making sure you include the proper headers and turned several things that used to just be warnings into errors.  These patches fix the ones I hit building from git on Solaris 11.4.  
- `file.c`: include `termios.h` if the system has it
- `usb_solaris.c`: include `bitfield.h` for definition of `putLittleEndian16`
- `rgx.c`: Use `RGX_INCLUDES` when building, in order to find `pcre2.h`
- `brlapi_client.c`: include `alloca.h` if the system has it
=> Fix builds on Solaris with gcc 14

Documents/brltty.conf.in, Drivers/Speech/SpeechDispatcher/README, Drivers/Speech/SpeechDispatcher/speech.c
This subsumes the removed port parameter.
If the address parameter is passed to the driver, its contents gets
put in the SPEECHD_ADDRESS environment vriable so that libspeechd
can use it. If the environment variable has already been set, the
driver parameter does not overwrite it.
This implements a suggestion from @sthibaul
=> Add the address parameter to the speech-dispatcher speech driver

Drivers/Screen/AtSpi2/a2_screen.c
We will not get any content anyway, and trying to call GetText on the will make them emit warnings:
CRITICAL **: 14:14:10.233: impl_GetText: assertion 'ATK_IS_TEXT (user_data)' failed
=> AtSpi2: do not manage widgets without text interface
